# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [
    "applesmc" # apple sudden motion sensor (can protect hdd)
    "brcmsmac" # wireless
    "kvm-intel" # for nix containers
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/16e8f2ea-fed4-49d7-9c73-1774a2b541bd";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BBCA-1CFC";
    fsType = "vfat";
  };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
